apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: c37ekf0wu-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c37ekf0wu-go 
  name: c37ekf0wu-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: c37ekf0wu-go 
